name: Package

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build

      - name: Create a zip
        run: zip -r sketch-crowdin.sketchplugin.zip sketch-crowdin.sketchplugin

      - name: Upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: sketch-crowdin.sketchplugin.zip
